services:
  app:
    build:
      context: .
      args:
        GIT_USERNAME: ${git_username}
        GIT_TOKEN: ${git_token}
    volumes:
      - .:/app
      - ./tmp:/app/tmp
      - /home/admin/.env:/root/.env
      - /WX2TB/Documentos:/WX2TB/Documentos
      - /projetos/arquivos/meteorologia:/projetos/arquivos/meteorologia
    environment:
      - modelo=${modelo}
      - data=${data}
      - hora=${hora}
      - resolucao=${resolucao}
      - produtos=null
      - sfcprefix=null
      - plprefix=null
