services:
  app:
    build:
      context: .
      args:
        GIT_USERNAME: ${git_username}
        GIT_TOKEN: ${git_token}
    volumes:
      - .:/app
      - ./tmp:/app/tmp
      - ~/.env:/root/.env
    environment:
      - modelo=${modelo}
      - data=${data}
      - hora=${hora}
      - resolucao=${resolucao}